/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Setting = {
  _id: string;
  _type: "setting";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  timezone?: string;
};

export type TwoFactorToken = {
  _id: string;
  _type: "twoFactorToken";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier?: string;
  token?: string;
  expires?: string;
};

export type PasswordResetToken = {
  _id: string;
  _type: "passwordResetToken";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier?: string;
  token?: string;
  expires?: string;
};

export type VerificationToken = {
  _id: string;
  _type: "verificationToken";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  identifier?: string;
  token?: string;
  expires?: string;
};

export type Session = {
  _id: string;
  _type: "session";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sessionToken?: string;
  userId?: string;
  expires?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  emailVerified?: string;
  image?: string;
  password?: string;
  role?: "ADMIN" | "USER";
  accounts?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "account";
  };
  isTwoFactorEnabled?: boolean;
  twoFactorConfirmation?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "twoFactorConfirmation";
  };
};

export type TwoFactorConfirmation = {
  _id: string;
  _type: "twoFactorConfirmation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
};

export type Account = {
  _id: string;
  _type: "account";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  type?: string;
  provider?: string;
  providerAccountId?: string;
  refreshToken?: string;
  accessToken?: string;
  expiresAt?: number;
  tokenType?: string;
  scope?: string;
  idToken?: string;
  sessionState?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
};

export type Appointment = {
  _id: string;
  _type: "appointment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  startTime?: string;
  endTime?: string;
  duration?: number;
  note?: string;
  reminder?: Array<"1h" | "2h" | "12h" | "24h" | "2d">;
  reminderDateTimes?: Array<string>;
  smsMessage?: string;
  employee?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "employee";
  };
  customer?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "customer";
  };
  service?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "service";
  };
  status?: "scheduled" | "completed" | "cancelled";
  recurringGroupId?: string;
};

export type AssignedService = {
  _type: "assignedService";
  serviceId: string;
  price: number;
  duration: number;
  processTime: number;
  showOnline: boolean;
};

export type WorkingTime = {
  _type: "workingTime";
  from: string;
  to: string;
  day?: string;
};

export type TimeOffSchedule = {
  _type: "timeOffSchedule";
  date?: string;
  from: string;
  to: string;
  reason?: string;
  dayOfWeek?: Array<number>;
  dayOfMonth?: Array<number>;
  period?: "Exact" | "Daily" | "Weekly" | "Monthly";
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
};

export type Employee = {
  _id: string;
  _type: "employee";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  fullName?: string;
  phone?: string;
  position?: "owner" | "serviceProvider" | "backRoom";
  workingTimes?: Array<
    {
      _key: string;
    } & WorkingTime
  >;
  timeOffSchedules?: Array<
    {
      _key: string;
    } & TimeOffSchedule
  >;
  assignedServices?: Array<
    {
      _key: string;
    } & AssignedService
  >;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "category";
  };
  name?: string;
  price?: number;
  duration?: number;
  showOnline?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Setting
  | TwoFactorToken
  | PasswordResetToken
  | VerificationToken
  | Session
  | User
  | TwoFactorConfirmation
  | Account
  | Appointment
  | AssignedService
  | WorkingTime
  | TimeOffSchedule
  | Customer
  | Employee
  | Service
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
